### ISSUE TITLE
ActionView::Template::Error: Missing partial 

### ISSUE THREAD

**Issue by dancancro** [davetron5000/angular-rails-book#40]
In step 2.3, "Tests", my tests are failing with the following output when I run 
> rake db:migrate RAILS_ENV=test ; rspec spec/controllers/recipes_controller_spec.rb

```
[20:12:25] (master) receta
// ♥ rake db:migrate RAILS_ENV=test ; rspec spec/controllers/recipes_controller_spec.rb
.FFFF

Failures:

  1) RecipesController index when the search finds results should include 'Baked Brussel Sprouts'
     Failure/Error: xhr :get, :index, format: :json, keywords: keywords
     ActionView::Template::Error:
       Missing partial recipes/_recipe, application/_recipe with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}. Searched in:
         * "/Users/Dan/work/angular-rails/receta/app/views"
     # ./app/views/recipes/index.json.jbuilder:1:in `_app_views_recipes_index_json_jbuilder___2543389150451662351_70112294416720'
     # ./spec/controllers/recipes_controller_spec.rb:12:in `block (3 levels) in <top (required)>'

  2) RecipesController index when the search finds results should return two results
     Failure/Error: xhr :get, :index, format: :json, keywords: keywords
     ActionView::Template::Error:
       Missing partial recipes/_recipe, application/_recipe with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}. Searched in:
         * "/Users/Dan/work/angular-rails/receta/app/views"
     # ./app/views/recipes/index.json.jbuilder:1:in `_app_views_recipes_index_json_jbuilder___2543389150451662351_70112294416720'
     # ./spec/controllers/recipes_controller_spec.rb:12:in `block (3 levels) in <top (required)>'

  3) RecipesController index when the search finds results should include 'Baked Potato w/ Cheese'
     Failure/Error: xhr :get, :index, format: :json, keywords: keywords
     ActionView::Template::Error:
       Missing partial recipes/_recipe, application/_recipe with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}. Searched in:
         * "/Users/Dan/work/angular-rails/receta/app/views"
     # ./app/views/recipes/index.json.jbuilder:1:in `_app_views_recipes_index_json_jbuilder___2543389150451662351_70112294416720'
     # ./spec/controllers/recipes_controller_spec.rb:12:in `block (3 levels) in <top (required)>'

  4) RecipesController index when the search finds results should 200
     Failure/Error: xhr :get, :index, format: :json, keywords: keywords
     ActionView::Template::Error:
       Missing partial recipes/_recipe, application/_recipe with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}. Searched in:
         * "/Users/Dan/work/angular-rails/receta/app/views"
     # ./app/views/recipes/index.json.jbuilder:1:in `_app_views_recipes_index_json_jbuilder___2543389150451662351_70112294416720'
     # ./spec/controllers/recipes_controller_spec.rb:12:in `block (3 levels) in <top (required)>'

Finished in 0.33643 seconds
5 examples, 4 failures

Failed examples:

rspec ./spec/controllers/recipes_controller_spec.rb:32 # RecipesController index when the search finds results should include 'Baked Brussel Sprouts'
rspec ./spec/controllers/recipes_controller_spec.rb:26 # RecipesController index when the search finds results should return two results
rspec ./spec/controllers/recipes_controller_spec.rb:29 # RecipesController index when the search finds results should include 'Baked Potato w/ Cheese'
rspec ./spec/controllers/recipes_controller_spec.rb:23 # RecipesController index when the search finds results should 200

Randomized with seed 53057
```

**Comment by davetron5000** [comment]
What's in your `index.json.jbuilder`?  It looks like it's trying to find `_receipt.json.jbuilder` and that file doesn't exist.

**Comment by dancancro** [comment]
```
json.array! @recipes, partial: 'recipe', as: :recipe
```

**Comment by davetron5000** [comment]
Get ready to be annoyed!  You've got `_recipe.json.builder`, not `_recipe.json.jbuilder` (note the "j" in "jbuilder").

I *hate* these, but at least it's an easy fix! :)

**Comment by dancancro** [comment]
Thank you

**Comment by realchrislee** [comment]
Thank you
