### ISSUE TITLE
 NoMethodError: undefined method `xhr'

### ISSUE THREAD

**Issue by dancancro** [davetron5000/angular-rails-book#41]
This is happening in [section 3.2 "Rails controller"](http://angular-rails.com/view_recipe.html#rails-controller). 

When I run `rspec spec/controllers/recipes_controller_spec.rb`, I get this:

```
// ♥ rspec spec/controllers/recipes_controller_spec.rb
FFFFF.....

Failures:

  1) show when the recipe exists 
     Failure/Error: xhr :get, :show, format: :json, id: recipe_id
     NoMethodError:
       undefined method `xhr' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007fefb9ee3558>
     # ./app/controllers/recipes_controller.rb:12:in `block (2 levels) in <class:RecipesController>'

  2) show when the recipe exists 
     Failure/Error: xhr :get, :show, format: :json, id: recipe_id
     NoMethodError:
       undefined method `xhr' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007fefb9e82aa0>
     # ./app/controllers/recipes_controller.rb:12:in `block (2 levels) in <class:RecipesController>'

  3) show when the recipe exists 
     Failure/Error: xhr :get, :show, format: :json, id: recipe_id
     NoMethodError:
       undefined method `xhr' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007fefb9e69820>
     # ./app/controllers/recipes_controller.rb:12:in `block (2 levels) in <class:RecipesController>'

  4) show when the recipe exists 
     Failure/Error: xhr :get, :show, format: :json, id: recipe_id
     NoMethodError:
       undefined method `xhr' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007fefb9e50dc0>
     # ./app/controllers/recipes_controller.rb:12:in `block (2 levels) in <class:RecipesController>'

  5) show when the recipe doesn't exit 
     Failure/Error: xhr :get, :show, format: :json, id: recipe_id
     NoMethodError:
       undefined method `xhr' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_2:0x007fefbd972930>
     # ./app/controllers/recipes_controller.rb:12:in `block (2 levels) in <class:RecipesController>'

Finished in 0.43231 seconds
10 examples, 5 failures

Failed examples:

rspec ./app/controllers/recipes_controller.rb:24 # show when the recipe exists 
rspec ./app/controllers/recipes_controller.rb:27 # show when the recipe exists 
rspec ./app/controllers/recipes_controller.rb:25 # show when the recipe exists 
rspec ./app/controllers/recipes_controller.rb:26 # show when the recipe exists 
rspec ./app/controllers/recipes_controller.rb:32 # show when the recipe doesn't exit 

Randomized with seed 64006

```

My code is on github [here](https://github.com/dancancro/receta-dan)

**Comment by davetron5000** [comment]
Only difference I can see is that you are not using RSpec 3.  Can you try using the latest RSpec?  The `xhr` method is provided by Rails' testing framework and RSpec should be bringing it in.

**Comment by dancancro** [comment]
I changed my Gemfile to match the one in the functioning fork of your finished product.  Then I ran bundle update and bundle install.  It says it's using rspec-core 3.3.1 and rspec 3.3.0, but it's still giving me the same error. I'm very new to Rails so thanks for your patience.

I've updated the source on github [here](https://github.com/dancancro/receta-dan).

**Comment by davetron5000** [comment]
This was a really odd one.  The problem is that you have RSpec code in your controller: https://github.com/dancancro/receta-dan/blob/master/app/controllers/recipes_controller.rb#L10

It was staring me in the face the entire time, since the exception was coming fro the controller and not the spec.  If you move that code out of the controller and into the spec file (`spec/controllers/recipes_controller_spec.rb`) it should all work.

**Comment by dancancro** [comment]
Ugh. I really messed that one up.  Thanks for the help.
