### ISSUE TITLE
undefined method 'configure' for Teaspoon:Module

### ISSUE THREAD

**Issue by dancancro** [davetron5000/angular-rails-book#42]
This is happening in section 4.2 when I run `rake teaspoon`

```
// ♥ rake teaspoon
rake aborted!
NoMethodError: undefined method `configure' for Teaspoon:Module
/Users/Dan/work/angular-rails/receta/spec/teaspoon_env.rb:1:in `<top (required)>'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:40:in `require_env'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:23:in `block in require_environment'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:21:in `each'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:21:in `require_environment'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:7:in `load'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/console.rb:12:in `initialize'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/tasks/teaspoon.rake:5:in `new'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/tasks/teaspoon.rake:5:in `block in <top (required)>'
Tasks: TOP => teaspoon
(See full trace by running task with --trace)
```

I get the problem with both the [receta that I'm building](https://github.com/dancancro/receta-dan)  and [the finished one](https://github.com/davetron5000/receta).

**Comment by dancancro** [comment]
Hi folks.

Any chance someone could take a look at this? I can't really do anything until this one is figured out.

Thanks

**Comment by davetron5000** [comment]
Sorry, got wrapped up in other things.  I think the problem is the version of teaspoon has changed.  Can you try re-running the teaspoon initializer? `rails g | grep teaspoon` will get you the exact name.

* Re-run the initializer and allow it to overwrite whatever it complains about
* It will generate `specs/javascripts/spec_helper.js`, which you don't need as your `specs/javascripts/spec_helper.coffee` will work, so delete the `.js` one.

**Comment by dancancro** [comment]
same thing

```
[01:30:13] (master) receta
// ♥ rails g | grep teaspoon
  teaspoon:install
[01:30:29] (master) receta
// ♥ ls spec/javascripts/spec_helper.js
ls: spec/javascripts/spec_helper.js: No such file or directory
[01:30:46] (master) receta
// ♥ rake teaspoon
rake aborted!
NoMethodError: undefined method `configure' for Teaspoon:Module
/Users/Dan/work/angular-rails/receta/spec/teaspoon_env.rb:1:in `<top (required)>'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:40:in `require_env'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:23:in `block in require_environment'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:21:in `each'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:21:in `require_environment'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/environment.rb:7:in `load'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/teaspoon/console.rb:12:in `initialize'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/tasks/teaspoon.rake:5:in `new'
/Users/Dan/.rvm/gems/ruby-2.2.2/gems/teaspoon-0.7.9/lib/tasks/teaspoon.rake:5:in `block in <top (required)>'
Tasks: TOP => teaspoon
(See full trace by running task with --trace)
[01:31:13] (master) receta
// ♥ 
```
